apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 5up3r-S3cr3t-auth-t0k3n
    jsonData:
      version: Flux
      organization: influxdata-org
      defaultBucket: default
      tlsSkipVerify: true